/*####################### TABLE: TEAMS #########################*/
CREATE TABLE RZR.TEAMS
(
tmt_id NUMBER,
tmt_name VARCHAR2(100),
tmt_const_champ NUMBER,
tmt_last_season NUMBER
)
TABLESPACE RZRTABLESPACE;

CREATE INDEX RZR.TEAM_NAME_INDX ON RZR.TEAMS (tmt_name)
TABLESPACE RZRTABLESPACE;

ALTER TABLE RZR.TEAMS
ADD CONSTRAINT TMT_TMT_ID PRIMARY KEY (tmt_id);

ALTER TABLE RZR.TEAMS
ADD CONSTRAINT TMT_NAME_UNK UNIQUE (tmt_name);

CREATE SEQUENCE RZR.TEAMS_SEQ
MINVALUE 1
MAXVALUE 9999999999999999999999999999
START WITH 1
INCREMENT BY 1;
/*#############################################################*/

/*###################### TABLE: ENGINES #######################*/
CREATE TABLE RZR.ENGINES
(
eng_id NUMBER,
eng_name VARCHAR2(200),
eng_power NUMBER,
eng_is_ers VARCHAR2(1)
) TABLESPACE RZRTABLESPACE;

CREATE INDEX RZR.ENGINE_NAME_INDX ON RZR.ENGINES(eng_name)
TABLESPACE RZRTABLESPACE;

ALTER TABLE RZR.ENGINES
ADD CONSTRAINT ENG_ENG_ID PRIMARY KEY(eng_id);

ALTER TABLE RZR.ENGINES
ADD CONSTRAINT ENG_NAME_UNK UNIQUE (eng_name);

CREATE SEQUENCE RZR.ENGINES_SEQ
MINVALUE 1
MAXVALUE 9999999999999999999999999999
START WITH 1
INCREMENT BY 1;
/*#############################################################*/
